#!/usr/bin/bash

PACKAGES=$(checkupdates)
# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
     xfce4-terminal -e "yaourt -Syua && echo Done - Press enter to exit && read" -H
fi
URGENT_VALUE=25

if [[ $? -gt 0 ]]; then
  return
fi

PACKAGE_COUNT=$(checkupdates | wc -l)

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}" # full-text
  echo "${PACKAGE_COUNT}" # short-text
  echo ""
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
